export const ERROR_CODES = {
  // User errors
  PROFILE_LIMIT: 'PROFILE_LIMIT',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_VALIDATION: 'PROFILE_VALIDATION',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_PATH_INVALID: 'WORKSPACE_PATH_INVALID',
  SETTINGS_KEY_MISSING: 'SETTINGS_KEY_MISSING',
  SETTINGS_MODEL_MISSING: 'SETTINGS_MODEL_MISSING',
  ANALYSIS_NO_PROFILES: 'ANALYSIS_NO_PROFILES',
  ANALYSIS_NO_JIRA: 'ANALYSIS_NO_JIRA',
  IMPORT_PARSE_ERROR: 'IMPORT_PARSE_ERROR',

  // Integration errors — Jira
  JIRA_AUTH_FAILED: 'JIRA_AUTH_FAILED',
  JIRA_RATE_LIMITED: 'JIRA_RATE_LIMITED',
  JIRA_FETCH_FAILED: 'JIRA_FETCH_FAILED',
  JIRA_PROJECT_NOT_FOUND: 'JIRA_PROJECT_NOT_FOUND',

  // Integration errors — Confluence
  CONFLUENCE_AUTH_FAILED: 'CONFLUENCE_AUTH_FAILED',
  CONFLUENCE_RATE_LIMITED: 'CONFLUENCE_RATE_LIMITED',
  CONFLUENCE_FETCH_FAILED: 'CONFLUENCE_FETCH_FAILED',

  // Integration errors — GitHub
  GITHUB_AUTH_FAILED: 'GITHUB_AUTH_FAILED',
  GITHUB_RATE_LIMITED: 'GITHUB_RATE_LIMITED',
  GITHUB_FETCH_FAILED: 'GITHUB_FETCH_FAILED',
  LLM_AUTH_FAILED: 'LLM_AUTH_FAILED',
  LLM_RATE_LIMITED: 'LLM_RATE_LIMITED',
  LLM_MODEL_UNAVAILABLE: 'LLM_MODEL_UNAVAILABLE',
  LLM_CONTEXT_EXCEEDED: 'LLM_CONTEXT_EXCEEDED',
  LLM_REQUEST_FAILED: 'LLM_REQUEST_FAILED',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',

  // LLM output errors
  LLM_PARSE_ERROR: 'LLM_PARSE_ERROR',
  LLM_PARSE_FAILED: 'LLM_PARSE_FAILED',
  LLM_EVIDENCE_INVALID: 'LLM_EVIDENCE_INVALID',
  LLM_EMPTY_RESPONSE: 'LLM_EMPTY_RESPONSE',

  // Integration errors — Codebase Analysis
  CODEBASE_CLI_NOT_FOUND: 'CODEBASE_CLI_NOT_FOUND',
  CODEBASE_CLI_NOT_AUTHENTICATED: 'CODEBASE_CLI_NOT_AUTHENTICATED',
  CODEBASE_GIT_NOT_FOUND: 'CODEBASE_GIT_NOT_FOUND',
  CODEBASE_CLONE_FAILED: 'CODEBASE_CLONE_FAILED',
  CODEBASE_ANALYSIS_TIMEOUT: 'CODEBASE_ANALYSIS_TIMEOUT',
  CODEBASE_ANALYSIS_FAILED: 'CODEBASE_ANALYSIS_FAILED',
  CODEBASE_PARSE_FAILED: 'CODEBASE_PARSE_FAILED',

  // Chat action errors
  ACTION_CLI_NOT_FOUND: 'ACTION_CLI_NOT_FOUND',
  ACTION_CLI_TIMEOUT: 'ACTION_CLI_TIMEOUT',
  ACTION_EXECUTION_FAILED: 'ACTION_EXECUTION_FAILED',
  ACTION_PARSE_FAILED: 'ACTION_PARSE_FAILED',
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  ACTION_INVALID_STATUS: 'ACTION_INVALID_STATUS',

  // System errors
  DB_ERROR: 'DB_ERROR',
  FS_PERMISSION_DENIED: 'FS_PERMISSION_DENIED',
  FS_NOT_FOUND: 'FS_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class DomainError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly cause?: unknown
  ) {
    super(message);
    this.name = 'DomainError';
  }
}
